### ISSUE TITLE
GPL v3 licence makes it not suitable for me to use derivatives of HelmWrapper pkg 

### ISSUE THREAD

**Issue by denist-huma** [teejaded/helm-wrap#13]
Hey please @yann-soubeyrand @teejaded 
Do you have a strong opinion towards GPL v3? 
Apache v2 gives the same Permissions for user but demands less Conditions, I can use it in not OSS work.

**Comment by yann-soubeyrand** [comment]
Hey @denist-huma, that’s the purpose of the GPL to enforce people to contribute back their changes if they publish a derivative work :wink:

**Comment by denist-huma** [comment]
I don't ask an abstract question to you.
For example I can provide my contribution to solve #14. But I would not do it do a GPL v3 project, olny for Apache 2.0 project. Because my time is paid hourly by one company I cannot spend time on solving issues that cannot benifit my company.
One requirement I have is to keep my main product code private, so I cannot use any copyleft except Apache 2.0, BSD -or- MIT. It is in our workbook.

**Comment by yann-soubeyrand** [comment]
Hello @denist-huma, sorry, I wasn’t clear, I meant the GPL was chosen on purpose.
